package test;

import java.math.BigDecimal;
import java.math.MathContext;
import java.math.RoundingMode;
import com.kreative.openxion.math.FastMath;

public class FastMathTest {
	private static final BigDecimal TWO = BigDecimal.valueOf(2);
	private static final BigDecimal THREE = BigDecimal.valueOf(3);
	private static final BigDecimal FOUR = BigDecimal.valueOf(4);
	
	public static void main(String[] args) {
		FastMath m = FastMath.instance;
		MathContext mc = new MathContext(100, RoundingMode.HALF_EVEN);
		Double e = m.e(mc);
		Double pi = m.pi(mc);
		System.out.println(e);
		System.out.println(pi);
		System.out.println("cbrt:");
		System.out.println(m.cbrt(FOUR, mc));
		System.out.println(m.cbrt(THREE, mc));
		System.out.println(m.cbrt(TWO, mc));
		System.out.println(m.cbrt(BigDecimal.ONE, mc));
		System.out.println(m.cbrt(BigDecimal.ZERO, mc));
		System.out.println(m.cbrt(BigDecimal.ONE.negate(), mc));
		System.out.println(m.cbrt(TWO.negate(), mc));
		System.out.println(m.cbrt(THREE.negate(), mc));
		System.out.println(m.cbrt(FOUR.negate(), mc));
		System.out.println(m.cbrt(Double.POSITIVE_INFINITY, mc));
		System.out.println(m.cbrt(Double.NEGATIVE_INFINITY, mc));
		System.out.println(m.cbrt(Double.NaN, mc));
		System.out.println("cos:");
		System.out.println(m.cos(pi*-2, mc));
		System.out.println(m.cos(pi*-1.75, mc));
		System.out.println(m.cos(pi*-1.5, mc));
		System.out.println(m.cos(pi*-1.25, mc));
		System.out.println(m.cos(pi*-1, mc));
		System.out.println(m.cos(pi*-0.75, mc));
		System.out.println(m.cos(pi*-0.5, mc));
		System.out.println(m.cos(pi*-0.25, mc));
		System.out.println(m.cos(BigDecimal.ZERO, mc));
		System.out.println(m.cos(pi*0.25, mc));
		System.out.println(m.cos(pi*0.5, mc));
		System.out.println(m.cos(pi*0.75, mc));
		System.out.println(m.cos(pi, mc));
		System.out.println(m.cos(pi*1.25, mc));
		System.out.println(m.cos(pi*1.5, mc));
		System.out.println(m.cos(pi*1.75, mc));
		System.out.println(m.cos(pi*2, mc));
		System.out.println(m.cos(pi*2.25, mc));
		System.out.println(m.cos(pi*2.5, mc));
		System.out.println(m.cos(pi*2.75, mc));
		System.out.println(m.cos(pi*3, mc));
		System.out.println(m.cos(Double.POSITIVE_INFINITY, mc));
		System.out.println(m.cos(Double.NEGATIVE_INFINITY, mc));
		System.out.println(m.cos(Double.NaN, mc));
		System.out.println("cosh:");
		System.out.println(m.cosh(Double.NEGATIVE_INFINITY, mc));
		System.out.println(m.cosh(TWO.negate(), mc));
		System.out.println(m.cosh(BigDecimal.valueOf(1.5).negate(), mc));
		System.out.println(m.cosh(BigDecimal.ONE.negate(), mc));
		System.out.println(m.cosh(BigDecimal.valueOf(0.5).negate(), mc));
		System.out.println(m.cosh(BigDecimal.ZERO, mc));
		System.out.println(m.cosh(BigDecimal.valueOf(0.5), mc));
		System.out.println(m.cosh(BigDecimal.ONE, mc));
		System.out.println(m.cosh(BigDecimal.valueOf(1.5), mc));
		System.out.println(m.cosh(TWO, mc));
		System.out.println(m.cosh(Double.POSITIVE_INFINITY, mc));
		System.out.println(m.cosh(Double.NaN, mc));
		System.out.println("exp:");
		System.out.println(m.exp(Double.NEGATIVE_INFINITY, mc));
		System.out.println(m.exp(FOUR.negate(), mc));
		System.out.println(m.exp(THREE.negate(), mc));
		System.out.println(m.exp(TWO.negate(), mc));
		System.out.println(m.exp(BigDecimal.ONE.negate(), mc));
		System.out.println(m.exp(BigDecimal.ZERO, mc));
		System.out.println(m.exp(BigDecimal.ONE, mc));
		System.out.println(m.exp(TWO, mc));
		System.out.println(m.exp(THREE, mc));
		System.out.println(m.exp(FOUR, mc));
		System.out.println(m.exp(Double.POSITIVE_INFINITY, mc));
		System.out.println(m.exp(Double.NaN, mc));
		System.out.println("expm1:");
		System.out.println(m.expm1(Double.NEGATIVE_INFINITY, mc));
		System.out.println(m.expm1(FOUR.negate(), mc));
		System.out.println(m.expm1(THREE.negate(), mc));
		System.out.println(m.expm1(TWO.negate(), mc));
		System.out.println(m.expm1(BigDecimal.ONE.negate(), mc));
		System.out.println(m.expm1(BigDecimal.ZERO, mc));
		System.out.println(m.expm1(BigDecimal.ONE, mc));
		System.out.println(m.expm1(TWO, mc));
		System.out.println(m.expm1(THREE, mc));
		System.out.println(m.expm1(FOUR, mc));
		System.out.println(m.expm1(Double.POSITIVE_INFINITY, mc));
		System.out.println(m.expm1(Double.NaN, mc));
		System.out.println("log:");
		System.out.println(m.log(Double.NEGATIVE_INFINITY, mc));
		System.out.println(m.log(TWO.negate(), mc));
		System.out.println(m.log(BigDecimal.valueOf(1.5).negate(), mc));
		System.out.println(m.log(BigDecimal.ONE.negate(), mc));
		System.out.println(m.log(BigDecimal.valueOf(0.5).negate(), mc));
		System.out.println(m.log(BigDecimal.ZERO, mc));
		System.out.println(m.log(BigDecimal.valueOf(0.5), mc));
		System.out.println(m.log(BigDecimal.ONE, mc));
		System.out.println(m.log(BigDecimal.valueOf(1.5), mc));
		System.out.println(m.log(TWO, mc));
		System.out.println(m.log(e, mc));
		System.out.println(m.log(THREE, mc));
		System.out.println(m.log(pi, mc));
		System.out.println(m.log(FOUR, mc));
		System.out.println(m.log(BigDecimal.TEN, mc));
		System.out.println(m.log(Double.POSITIVE_INFINITY, mc));
		System.out.println(m.log(Double.NaN, mc));
		System.out.println("log10:");
		System.out.println(m.log10(Double.NEGATIVE_INFINITY, mc));
		System.out.println(m.log10(TWO.negate(), mc));
		System.out.println(m.log10(BigDecimal.valueOf(1.5).negate(), mc));
		System.out.println(m.log10(BigDecimal.ONE.negate(), mc));
		System.out.println(m.log10(BigDecimal.valueOf(0.5).negate(), mc));
		System.out.println(m.log10(BigDecimal.ZERO, mc));
		System.out.println(m.log10(BigDecimal.valueOf(0.5), mc));
		System.out.println(m.log10(BigDecimal.ONE, mc));
		System.out.println(m.log10(BigDecimal.valueOf(1.5), mc));
		System.out.println(m.log10(TWO, mc));
		System.out.println(m.log10(e, mc));
		System.out.println(m.log10(THREE, mc));
		System.out.println(m.log10(pi, mc));
		System.out.println(m.log10(FOUR, mc));
		System.out.println(m.log10(BigDecimal.TEN, mc));
		System.out.println(m.log10(Double.POSITIVE_INFINITY, mc));
		System.out.println(m.log10(Double.NaN, mc));
		System.out.println("log1p:");
		System.out.println(m.log1p(Double.NEGATIVE_INFINITY, mc));
		System.out.println(m.log1p(TWO.negate(), mc));
		System.out.println(m.log1p(BigDecimal.valueOf(1.5).negate(), mc));
		System.out.println(m.log1p(BigDecimal.ONE.negate(), mc));
		System.out.println(m.log1p(BigDecimal.valueOf(0.5).negate(), mc));
		System.out.println(m.log1p(BigDecimal.ZERO, mc));
		System.out.println(m.log1p(BigDecimal.valueOf(0.5), mc));
		System.out.println(m.log1p(BigDecimal.ONE, mc));
		System.out.println(m.log1p(BigDecimal.valueOf(1.5), mc));
		System.out.println(m.log1p(TWO, mc));
		System.out.println(m.log1p(e, mc));
		System.out.println(m.log1p(THREE, mc));
		System.out.println(m.log1p(pi, mc));
		System.out.println(m.log1p(FOUR, mc));
		System.out.println(m.log1p(BigDecimal.TEN, mc));
		System.out.println(m.log1p(Double.POSITIVE_INFINITY, mc));
		System.out.println(m.log1p(Double.NaN, mc));
		System.out.println("log2:");
		System.out.println(m.log2(Double.NEGATIVE_INFINITY, mc));
		System.out.println(m.log2(TWO.negate(), mc));
		System.out.println(m.log2(BigDecimal.valueOf(1.5).negate(), mc));
		System.out.println(m.log2(BigDecimal.ONE.negate(), mc));
		System.out.println(m.log2(BigDecimal.valueOf(0.5).negate(), mc));
		System.out.println(m.log2(BigDecimal.ZERO, mc));
		System.out.println(m.log2(BigDecimal.valueOf(0.5), mc));
		System.out.println(m.log2(BigDecimal.ONE, mc));
		System.out.println(m.log2(BigDecimal.valueOf(1.5), mc));
		System.out.println(m.log2(TWO, mc));
		System.out.println(m.log2(e, mc));
		System.out.println(m.log2(THREE, mc));
		System.out.println(m.log2(pi, mc));
		System.out.println(m.log2(FOUR, mc));
		System.out.println(m.log2(BigDecimal.TEN, mc));
		System.out.println(m.log2(Double.POSITIVE_INFINITY, mc));
		System.out.println(m.log2(Double.NaN, mc));
		System.out.println("sin:");
		System.out.println(m.sin(pi*-2, mc));
		System.out.println(m.sin(pi*-1.75, mc));
		System.out.println(m.sin(pi*-1.5, mc));
		System.out.println(m.sin(pi*-1.25, mc));
		System.out.println(m.sin(pi*-1, mc));
		System.out.println(m.sin(pi*-0.75, mc));
		System.out.println(m.sin(pi*-0.5, mc));
		System.out.println(m.sin(pi*-0.25, mc));
		System.out.println(m.sin(BigDecimal.ZERO, mc));
		System.out.println(m.sin(pi*0.25, mc));
		System.out.println(m.sin(pi*0.5, mc));
		System.out.println(m.sin(pi*0.75, mc));
		System.out.println(m.sin(pi, mc));
		System.out.println(m.sin(pi*1.25, mc));
		System.out.println(m.sin(pi*1.5, mc));
		System.out.println(m.sin(pi*1.75, mc));
		System.out.println(m.sin(pi*2, mc));
		System.out.println(m.sin(pi*2.25, mc));
		System.out.println(m.sin(pi*2.5, mc));
		System.out.println(m.sin(pi*2.75, mc));
		System.out.println(m.sin(pi*3, mc));
		System.out.println(m.sin(Double.POSITIVE_INFINITY, mc));
		System.out.println(m.sin(Double.NEGATIVE_INFINITY, mc));
		System.out.println(m.sin(Double.NaN, mc));
		System.out.println("sinh:");
		System.out.println(m.sinh(Double.NEGATIVE_INFINITY, mc));
		System.out.println(m.sinh(TWO.negate(), mc));
		System.out.println(m.sinh(BigDecimal.valueOf(1.5).negate(), mc));
		System.out.println(m.sinh(BigDecimal.ONE.negate(), mc));
		System.out.println(m.sinh(BigDecimal.valueOf(0.5).negate(), mc));
		System.out.println(m.sinh(BigDecimal.ZERO, mc));
		System.out.println(m.sinh(BigDecimal.valueOf(0.5), mc));
		System.out.println(m.sinh(BigDecimal.ONE, mc));
		System.out.println(m.sinh(BigDecimal.valueOf(1.5), mc));
		System.out.println(m.sinh(TWO, mc));
		System.out.println(m.sinh(Double.POSITIVE_INFINITY, mc));
		System.out.println(m.sinh(Double.NaN, mc));
		System.out.println("sqrt:");
		System.out.println(m.sqrt(FOUR, mc));
		System.out.println(m.sqrt(THREE, mc));
		System.out.println(m.sqrt(TWO, mc));
		System.out.println(m.sqrt(BigDecimal.ONE, mc));
		System.out.println(m.sqrt(BigDecimal.ZERO, mc));
		System.out.println(m.sqrt(BigDecimal.ONE.negate(), mc));
		System.out.println(m.sqrt(TWO.negate(), mc));
		System.out.println(m.sqrt(THREE.negate(), mc));
		System.out.println(m.sqrt(FOUR.negate(), mc));
		System.out.println(m.sqrt(Double.POSITIVE_INFINITY, mc));
		System.out.println(m.sqrt(Double.NEGATIVE_INFINITY, mc));
		System.out.println(m.sqrt(Double.NaN, mc));
		System.out.println("tan:");
		System.out.println(m.tan(pi*-2, mc));
		System.out.println(m.tan(pi*-1.75, mc));
		System.out.println(m.tan(pi*-1.5, mc));
		System.out.println(m.tan(pi*-1.25, mc));
		System.out.println(m.tan(pi*-1, mc));
		System.out.println(m.tan(pi*-0.75, mc));
		System.out.println(m.tan(pi*-0.5, mc));
		System.out.println(m.tan(pi*-0.25, mc));
		System.out.println(m.tan(BigDecimal.ZERO, mc));
		System.out.println(m.tan(pi*0.25, mc));
		System.out.println(m.tan(pi*0.5, mc));
		System.out.println(m.tan(pi*0.75, mc));
		System.out.println(m.tan(pi, mc));
		System.out.println(m.tan(pi*1.25, mc));
		System.out.println(m.tan(pi*1.5, mc));
		System.out.println(m.tan(pi*1.75, mc));
		System.out.println(m.tan(pi*2, mc));
		System.out.println(m.tan(pi*2.25, mc));
		System.out.println(m.tan(pi*2.5, mc));
		System.out.println(m.tan(pi*2.75, mc));
		System.out.println(m.tan(pi*3, mc));
		System.out.println(m.tan(Double.POSITIVE_INFINITY, mc));
		System.out.println(m.tan(Double.NEGATIVE_INFINITY, mc));
		System.out.println(m.tan(Double.NaN, mc));
		System.out.println(m.tan(pi*-0.5, mc));
		System.out.println(m.tan(pi*-0.375, mc));
		System.out.println(m.tan(pi*-0.25, mc));
		System.out.println(m.tan(pi*-0.125, mc));
		System.out.println(m.tan(BigDecimal.ZERO, mc));
		System.out.println(m.tan(pi*0.125, mc));
		System.out.println(m.tan(pi*0.25, mc));
		System.out.println(m.tan(pi*0.375, mc));
		System.out.println(m.tan(pi*0.5, mc));
		System.out.println("tanh:");
		System.out.println(m.tanh(Double.NEGATIVE_INFINITY, mc));
		System.out.println(m.tanh(TWO.negate(), mc));
		System.out.println(m.tanh(BigDecimal.valueOf(1.5).negate(), mc));
		System.out.println(m.tanh(BigDecimal.ONE.negate(), mc));
		System.out.println(m.tanh(BigDecimal.valueOf(0.5).negate(), mc));
		System.out.println(m.tanh(BigDecimal.ZERO, mc));
		System.out.println(m.tanh(BigDecimal.valueOf(0.5), mc));
		System.out.println(m.tanh(BigDecimal.ONE, mc));
		System.out.println(m.tanh(BigDecimal.valueOf(1.5), mc));
		System.out.println(m.tanh(TWO, mc));
		System.out.println(m.tanh(Double.POSITIVE_INFINITY, mc));
		System.out.println(m.tanh(Double.NaN, mc));
	}
}
